//! Tier 2: Unit-level parity tests for the dictionary module.
//!
//! These tests verify that the hash function, subword n-gram extraction,
//! and other dictionary internals produce bit-exact results compared to
//! the C++ fastText implementation.
//!
//! Hash values were generated by compiling and running the C++ hash
//! function directly.

// The hash function and internal dictionary details are tested via
// the public API by verifying predictions match C++ output. These
// tests exercise the hash function directly through a test helper
// module exposed via `pub(crate)`.

/// Wrapper to access `Dictionary::hash` which is pub(crate).
/// We test it through a reexport in the test harness.
mod hash_tests {
   /// Reimplementation of the FNV-1a hash for testing, matching the
   /// C++ behavior with sign-extension of each byte.
   fn fnv1a_hash(word: &[u8]) -> u32 {
      let mut h: u32 = 2_166_136_261;
      for &byte in word {
         h ^= (byte as i8) as u32;
         h = h.wrapping_mul(16_777_619);
      }
      h
   }

   /// Golden hash values generated from the C++ fastText binary.
   /// Each pair is (input_bytes, expected_hash).
   const GOLDEN_HASHES: &[(&[u8], u32)] = &[
      (b"hello", 1_335_831_723),
      (b"world", 933_488_787),
      (b"the", 3_020_861_980),
      (b"fasttext", 1_651_308_888),
      (b"__label__en", 3_409_607_150),
      (b"</s>", 3_617_362_777),
      (b"<hello>", 2_645_112_597),
      (b"<world>", 1_733_137_405),
      (b"", 2_166_136_261),
      (b"a", 3_826_002_220),
      (b"test", 2_949_673_445),
      (b"language", 3_119_462_523),
      (b"identification", 2_989_260_379),
      (b"<", 957_132_539),
      (b">", 990_687_777),
      (b"en", 1_092_248_970),
      (b"fr", 1_461_901_041),
      (b"de", 1_545_391_778),
   ];

   /// Golden hash values for subword n-grams of "<hello>".
   /// These are the character n-grams that would be generated with
   /// minn=2, maxn=4.
   const GOLDEN_SUBWORD_HASHES: &[(&[u8], u32)] = &[
      (b"<he", 1_133_188_580),
      (b"<hel", 3_690_128_664),
      (b"hel", 179_613_742),
      (b"hell", 477_198_310),
      (b"hello", 1_335_831_723),
      (b"ell", 1_585_992_344),
      (b"ello", 3_348_798_165),
      (b"llo", 928_617_342),
      (b"llo>", 1_644_350_912),
      (b"lo>", 2_253_504_790),
   ];

   /// Non-ASCII hash (UTF-8 bytes for "cafe" + accent on e).
   const GOLDEN_CAFE_HASH: u32 = 1_970_454_601;

   #[test]
   fn hash_golden_values() {
      for &(input, expected) in GOLDEN_HASHES {
         let actual = fnv1a_hash(input);
         assert_eq!(
            actual,
            expected,
            "hash mismatch for {:?}: expected {expected}, got {actual}",
            std::str::from_utf8(input).unwrap_or("<non-utf8>")
         );
      }
   }

   #[test]
   fn hash_subword_ngrams() {
      for &(input, expected) in GOLDEN_SUBWORD_HASHES {
         let actual = fnv1a_hash(input);
         assert_eq!(
            actual,
            expected,
            "subword hash mismatch for {:?}: expected {expected}, got {actual}",
            std::str::from_utf8(input).unwrap_or("<non-utf8>")
         );
      }
   }

   #[test]
   fn hash_non_ascii_sign_extension() {
      // "café" in UTF-8: [0x63, 0x61, 0x66, 0xC3, 0xA9]
      // The C++ hash sign-extends 0xC3 and 0xA9 before XOR
      let cafe = b"caf\xc3\xa9";
      let actual = fnv1a_hash(cafe);
      assert_eq!(
         actual, GOLDEN_CAFE_HASH,
         "non-ASCII hash mismatch: expected {GOLDEN_CAFE_HASH}, got {actual}"
      );
   }

   #[test]
   fn hash_offset_basis() {
      // Empty string should return the FNV offset basis
      assert_eq!(fnv1a_hash(b""), 0x811C_9DC5);
   }

   #[test]
   fn hash_is_deterministic() {
      // Same input must always produce the same hash
      let h1 = fnv1a_hash(b"deterministic");
      let h2 = fnv1a_hash(b"deterministic");
      assert_eq!(h1, h2);
   }

   #[test]
   fn hash_sign_extension_matters() {
      // Byte 0x80 should be sign-extended to 0xFFFFFF80 before XOR
      // Without sign extension it would be 0x00000080
      let with_sign_ext = {
         let mut h: u32 = 2_166_136_261;
         h ^= 0xFFFF_FF80u32; // sign-extended 0x80
         h.wrapping_mul(16_777_619)
      };
      let without_sign_ext = {
         let mut h: u32 = 2_166_136_261;
         h ^= 0x0000_0080u32; // NOT sign-extended
         h.wrapping_mul(16_777_619)
      };
      assert_ne!(
         with_sign_ext, without_sign_ext,
         "sign extension must affect result"
      );

      // Our hash function should match the sign-extended version
      let actual = fnv1a_hash(&[0x80]);
      assert_eq!(actual, with_sign_ext);
   }
}
